# Generated by Django 5.1.4 on 2025-01-02 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'artist',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('music_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('youtube_url', models.URLField(blank=True, max_length=500, null=True)),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('features', models.JSONField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.artist')),
            ],
            options={
                'db_table': 'music',
                'managed': True,
            },
        ),
    ]
