# Generated by Django 5.1.4 on 2025-01-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='artist_id',
            new_name='artist',
        ),
    ]
