# Generated by Django 5.1.4 on 2025-01-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='preview_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
